"""
Hashing: -
 - It is a data structure technique used to efficiently store and retrieve data in constant time complexity, O(1) on average
 - Key: The raw data item input (such as an ID number, employee name, or product string) that needs to be stored or searched.
 - Hash Function: The mathematical algorithm or formula that processes the key and computes its corresponding integer index.
 - Hash Table: An array-based data structure that stores the actual key-value pairs at the indices generated by the hash function
"""

class hashing:
    def __init__(self):
        self.__mod = 10
        self.__key = 100
        self.__data = [None] * self.__mod
        self.__keys = [None] * self.__mod

    def __hashFunction(self, key, mod):
        return key % mod

    def addData(self, addData, specificKey = None):
        if specificKey is None:
            index = self.__hashFunction(key=self.__key, mod=self.__mod)

            if self.__data[index] is None:
                self.__data[index] = addData
                self.__keys[index] = self.__key
                self.__key += 1
                return self.__keys[index]
            else:
                return False
            
        else:
            index = self.__hashFunction(key=specificKey, mod=self.__mod)

            if self.__data[index] is None:
                self.__data[index] = addData
                self.__keys[index] = specificKey
                return self.__keys[index]
            else:
                return False

    def retrieveData(self, retrieveKey):
        if retrieveKey > 0:
            index = self.__hashFunction(key=retrieveKey, mod=self.__mod)
        else:
            return False     

        if self.__keys[index] == retrieveKey:
            return self.__data[index]
        else:
            return False
    
    def rehashing(self):
        tempData = self.__data
        tempKeys = self.__keys
        tempMod = self.__mod

        self.__mod += self.__mod
        self.__data = [None] * self.__mod
        self.__keys = [None] * self.__mod

        for i in tempKeys:
            if i is not None:
                idx = self.__hashFunction(key=i, mod=tempMod)
                data = tempData[idx]
                self.addData(data, specificKey=i)

        return len(self.__keys)


def main():
    h = hashing()
    print(f'Default table length is 10 rows')

    while True:
        check = None
        print('___________________________________________________________________________\n')

        print('To add data enter      --> 1')
        print('To retrieve data enter --> 2')
        print('To exit enter          --> 0\n')

        while True:
            try:
                choice = int(input('Enter your choice: '))
                break
            except ValueError:
                print('Choice must be an integer value! Please enter a value again:')

        print('___________________________________________________________________________\n')

        if choice == 0:
            break

        elif choice == 1:
            d = input('Enter your data: ')
            check = h.addData(d)

            if check:
                print('Successfully added your data.')
                print(f'Your data key is: {check}')
            else:
                print('Failed to add data. maybe be table is full!')
                o = input('To increase table size enter --> Y: ')
                if o == 'Y' or o == 'y':
                    size = h.rehashing()
                    print(f'Table size incresed to {size}')
        
        elif choice == 2:
            while True:
                try:
                    key = int(input('Enter your key: '))
                    break
                except ValueError:
                    print('Key must be an integer value! Please enter the key again:')
            r = h.retrieveData(key)
            print('___________________________________________________________________________\n')
            if type(r) is not bool:
                print(f'Your data is: {r}')
            else:
                print(f'Key {key} does not exist in the table')
                
        else:
            print('Invalid choice!')

if __name__ == '__main__':
    main()