"""
Hashing: -
 - It is a data structure technique used to efficiently store and retrieve data in constant time complexity, O(1) on average
 - Key: The raw data item input (such as an ID number, employee name, or product string) that needs to be stored or searched.
 - Hash Function: The mathematical algorithm or formula that processes the key and computes its corresponding integer index.
 - Hash Table: An array-based data structure that stores the actual key-value pairs at the indices generated by the hash function
"""

class hashing:
    def __init__(self):
        self.__mod = 10
        self.__data = [None] * self.__mod
        self.__keys = [None] * self.__mod
        self.filledData = 0

    def __hashFunction(self, key, mod):
        return key % mod

    def addData(self, addData, specificKey):
        index = self.__hashFunction(key=specificKey, mod=self.__mod)

        if (self.filledData / self.__mod) >= 0.75:
            return False
        
        elif self.__data[index] is None:
            self.__data[index] = addData
            self.__keys[index] = specificKey
            self.filledData += 1
            return True
        
        elif self.__keys[index] == specificKey:
            self.__data[index] = addData
            return True
        
        else:
            tempKey = specificKey
            while True:
                tempKey += 1
                index = self.__hashFunction(key=tempKey, mod=self.__mod)
                
                if self.__data[index] is None:
                    self.__data[index] = addData
                    self.__keys[index] = specificKey
                    self.filledData += 1
                    break
                elif self.__keys[index] == specificKey:
                    self.__data[index] = addData
                    break
            return True
                
    def retrieveData(self, retrieveKey):
        
        index = self.__hashFunction(key=retrieveKey, mod=self.__mod)

        if self.__keys[index] == retrieveKey:
            return self.__data[index]
        else:
            tempKey = retrieveKey
            keyFound = False
            while True:
                tempKey += 1
                index = self.__hashFunction(key=tempKey, mod=self.__mod)
                if self.__keys[index] == retrieveKey:
                    keyFound = True
                    break
                elif self.__keys[index] == None:
                    break

            if keyFound:
                return self.__data[index]
            else:
                return False
    
    def rehashing(self):
        tempData = self.__data
        tempKeys = self.__keys
        tempMod = self.__mod

        self.__mod += self.__mod
        self.__data = [None] * self.__mod
        self.__keys = [None] * self.__mod
        self.filledData = 0

        for i in range(len(tempKeys)):
            key = tempKeys[i]
            if tempKeys[i] is not None:
                data = tempData[i]
                self.addData(addData=data, specificKey=key)

        return len(self.__keys)


def main():
    h = hashing()
    print(f'Default table length is 10 rows')

    while True:
        check = None
        print('___________________________________________________________________________\n')

        print('To add data enter      --> 1')
        print('To retrieve data enter --> 2')
        print('To exit enter          --> 0\n')

        while True:
            try:
                choice = int(input('Enter your choice: '))
                break
            except ValueError:
                print('Choice must be an integer value! Please enter a value again:')

        print('___________________________________________________________________________\n')

        if choice == 0:
            break

        elif choice == 1:
            while True:
                try:
                    addKey = int(input('Enter your key for data: '))
                    break
                except ValueError:
                    print('Key must be an integer value! Please enter the key again:')

            data = input('Enter your data: ')

            check = h.addData(addData=data, specificKey=addKey)

            if check:
                print('Successfully added your data.')
            else:
                print('Failed to add data. maybe be table is full!')
                o = input('To increase table size enter --> Y: ')
                if o == 'Y' or o == 'y':
                    size = h.rehashing()
                    print(f'Table size incresed to {size}')
        
        elif choice == 2:
            while True:
                try:
                    key = int(input('Enter your key: '))
                    break
                except ValueError:
                    print('Key must be an integer value! Please enter the key again:')
            r = h.retrieveData(key)
            print('___________________________________________________________________________\n')
            if type(r) is not bool:
                print(f'Your data is: {r}')
            else:
                print(f'Key {key} does not exist in the table')
                
        else:
            print('Invalid choice!')

if __name__ == '__main__':
    main()